packages:
  - packages/**
  - tooling/*
  - apps/*
  - '!**/build/**'
  - '!**/dist/**'
  - '!**/out/**'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js-pure
  - es5-ext
  - esbuild
  - fsevents
  - msgpackr-extract
  - protobufjs
  - sharp
