packages:
  - packages/**
  - tooling/*
  - apps/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js-pure
  - es5-ext
  - esbuild
  - fsevents
  - msgpackr-extract
  - protobufjs
  - sharp
